hibernate.connection.url=jdbc:mysql://localhost:3306/hbn_pr
hibernate.connection.user=root
hibernate.connection.password=Dipesh@9092
hibernate.hbm2ddl.auto=create
hibernate.connection.driver=com.mysql.cj.jdbc.Driver
hibernate.show_sql=true
hibernate.cache.use_second_level_cache=true
hibernate.cache.region.factory_class=org.hibernate.cache.ehcache.internal.EhcacheRegionFactory